update deps + loosen some requirements (#208)
* update deps + loosen some requirements

rules:
- for crates that are below v1.0 -> specify the precise version
- If the code uses a feature that was added for example in X 0.3.17,
  then you should specify 0.3.17, which actually means "0.3.y where y >=
  17"
- for crates the are above or equal v1.0 -> specify only major version
  if the crate's API is minimal and won't change between minor versions
    OR specify major&minor versions otherwise

tested with https://github.com/taiki-e/cargo-minimal-versions

* fix branch name

* update min supported rust to 1.57

error: package `time v0.3.11` cannot be built because it requires rustc
1.57.0 or newer, while the currently active rustc version is 1.56.1
https://github.com/webrtc-rs/webrtc/runs/7409030752?check_suite_focus=true

* fix warnings

* specify min time dep version

* move time crate to runtime deps

* add link to PR