update deps + loosen some requirements (#22)
* update deps + loosen some requirements

rules:
- for crates that are below v1.0 -> specify the precise version
- If the code uses a feature that was added for example in X 0.3.17,
  then you should specify 0.3.17, which actually means "0.3.y where y >=
  17"
- for crates the are above or equal v1.0 -> specify only major version
  if the crate's API is minimal and won't change between minor versions
    OR specify major&minor versions otherwise

tested with https://github.com/taiki-e/cargo-minimal-versions

* fix warnings

* bump min version

error: package `pkcs8 v0.9.0` cannot be built because it requires rustc
1.57 or newer, while the currently active rustc version is 1.56.1

* update util version

* use cargo cache in minimal-versions job

* Revert "use cargo cache in minimal-versions job"

This reverts commit d58d33f175e7bc103347e7a80548ae64775713b5.

* update oid-registry, x509-parser and der-parser

* update rcgen

* update x509-parser

 and restrict hkdf and curve25519-dalek versions so minimal-dependencies
 job passes on CI